/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksSyncMediaRouteImport } from './routes/api/public/hooks/sync-media'

const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncMediaRoute = ApiPublicHooksSyncMediaRouteImport.update({
  id: '/api/public/hooks/sync-media',
  path: '/api/public/hooks/sync-media',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/triage': typeof TriageRoute
  '/api/public/hooks/sync-media': typeof ApiPublicHooksSyncMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/triage': typeof TriageRoute
  '/api/public/hooks/sync-media': typeof ApiPublicHooksSyncMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/triage': typeof TriageRoute
  '/api/public/hooks/sync-media': typeof ApiPublicHooksSyncMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lists' | '/triage' | '/api/public/hooks/sync-media'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lists' | '/triage' | '/api/public/hooks/sync-media'
  id: '__root__' | '/' | '/lists' | '/triage' | '/api/public/hooks/sync-media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListsRoute: typeof ListsRoute
  TriageRoute: typeof TriageRoute
  ApiPublicHooksSyncMediaRoute: typeof ApiPublicHooksSyncMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-media': {
      id: '/api/public/hooks/sync-media'
      path: '/api/public/hooks/sync-media'
      fullPath: '/api/public/hooks/sync-media'
      preLoaderRoute: typeof ApiPublicHooksSyncMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListsRoute: ListsRoute,
  TriageRoute: TriageRoute,
  ApiPublicHooksSyncMediaRoute: ApiPublicHooksSyncMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
