/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksSyncMediaRouteImport } from './routes/api/public/hooks/sync-media'
import { Route as ApiPublicHooksBackfillMediaRouteImport } from './routes/api/public/hooks/backfill-media'

const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncMediaRoute = ApiPublicHooksSyncMediaRouteImport.update({
  id: '/api/public/hooks/sync-media',
  path: '/api/public/hooks/sync-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackfillMediaRoute =
  ApiPublicHooksBackfillMediaRouteImport.update({
    id: '/api/public/hooks/backfill-media',
    path: '/api/public/hooks/backfill-media',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/triage': typeof TriageRoute
  '/api/public/hooks/backfill-media': typeof ApiPublicHooksBackfillMediaRoute
  '/api/public/hooks/sync-media': typeof ApiPublicHooksSyncMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/triage': typeof TriageRoute
  '/api/public/hooks/backfill-media': typeof ApiPublicHooksBackfillMediaRoute
  '/api/public/hooks/sync-media': typeof ApiPublicHooksSyncMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/triage': typeof TriageRoute
  '/api/public/hooks/backfill-media': typeof ApiPublicHooksBackfillMediaRoute
  '/api/public/hooks/sync-media': typeof ApiPublicHooksSyncMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lists'
    | '/privacy'
    | '/terms'
    | '/triage'
    | '/api/public/hooks/backfill-media'
    | '/api/public/hooks/sync-media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lists'
    | '/privacy'
    | '/terms'
    | '/triage'
    | '/api/public/hooks/backfill-media'
    | '/api/public/hooks/sync-media'
  id:
    | '__root__'
    | '/'
    | '/lists'
    | '/privacy'
    | '/terms'
    | '/triage'
    | '/api/public/hooks/backfill-media'
    | '/api/public/hooks/sync-media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListsRoute: typeof ListsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TriageRoute: typeof TriageRoute
  ApiPublicHooksBackfillMediaRoute: typeof ApiPublicHooksBackfillMediaRoute
  ApiPublicHooksSyncMediaRoute: typeof ApiPublicHooksSyncMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-media': {
      id: '/api/public/hooks/sync-media'
      path: '/api/public/hooks/sync-media'
      fullPath: '/api/public/hooks/sync-media'
      preLoaderRoute: typeof ApiPublicHooksSyncMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-media': {
      id: '/api/public/hooks/backfill-media'
      path: '/api/public/hooks/backfill-media'
      fullPath: '/api/public/hooks/backfill-media'
      preLoaderRoute: typeof ApiPublicHooksBackfillMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListsRoute: ListsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TriageRoute: TriageRoute,
  ApiPublicHooksBackfillMediaRoute: ApiPublicHooksBackfillMediaRoute,
  ApiPublicHooksSyncMediaRoute: ApiPublicHooksSyncMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
