-- Record of the arcade content pack import already applied to the live
-- Supabase project (arcade_v1 item seed). The repo file is the record;
-- Lovable Cloud does not auto-apply it.
--
-- Source packs: scripts/packs/{quotes,emoji,sequels,trivia}.json.
-- quotes -> quote-match (120), emoji -> emoji (100), sequels ->
-- sequel-or-fake (90), trivia -> screening (90). 400 items total, 0 dropped.
--
-- quote-match and emoji items carry the answer as media_id, resolved against
-- media by exact case-insensitive title plus year within one (exact year and
-- highest vote_count win ties). Six pack titles were matched under the
-- catalog's TMDB naming rather than dropped, all verified by id at import
-- time: Harry Potter and the Sorcerer's Stone -> Philosopher's Stone
-- (movie-671), Deathly Hallows Part 2 -> Deathly Hallows: Part 2
-- (movie-12445), Monty Python's Life of Brian -> Life of Brian (movie-583),
-- National Lampoon's Animal House -> Animal House (movie-8469), Star Wars:
-- Episode I with a hyphen (movie-1893), WALL-E -> WALL·E (movie-10681).
--
-- The media_id values below are the ones that actually landed; payloads keep
-- only the game fields (quote/trap_titles, emoji/decoys,
-- title/year/real/anchor/reveal, q/choices/answer/note).

insert into public.arcade_items (game_slug, media_id, payload, difficulty, pack) values
  ('quote-match', 'movie-11', '{"quote": "May the Force be with you.", "trap_titles": ["The Empire Strikes Back", "Star Trek: The Motion Picture"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-218', '{"quote": "I''ll be back.", "trap_titles": ["Terminator 2: Judgment Day", "Predator"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-13', '{"quote": "Mama always said life was like a box of chocolates.", "trap_titles": ["The Green Mile", "Big"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-568', '{"quote": "Houston, we have a problem.", "trap_titles": ["Gravity", "Armageddon"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-597', '{"quote": "I''m the king of the world!", "trap_titles": ["The Aviator", "Romeo + Juliet"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-601', '{"quote": "E.T. phone home.", "trap_titles": ["Close Encounters of the Third Kind", "Flight of the Navigator"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-578', '{"quote": "You''re gonna need a bigger boat.", "trap_titles": ["Jurassic Park", "The Meg"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-745', '{"quote": "I see dead people.", "trap_titles": ["The Others", "Ghost"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-155', '{"quote": "Why so serious?", "trap_titles": ["Joker", "Batman Begins"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-111', '{"quote": "Say hello to my little friend!", "trap_titles": ["Carlito''s Way", "The Godfather Part III"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-103', '{"quote": "You talkin'' to me?", "trap_titles": ["Raging Bull", "Goodfellas"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-238', '{"quote": "I''m gonna make him an offer he can''t refuse.", "trap_titles": ["The Godfather Part II", "Goodfellas"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-881', '{"quote": "You can''t handle the truth!", "trap_titles": ["The Firm", "JFK"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-280', '{"quote": "Hasta la vista, baby.", "trap_titles": ["The Terminator", "Total Recall"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-862', '{"quote": "To infinity and beyond!", "trap_titles": ["Toy Story 2", "Lightyear"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-12', '{"quote": "Just keep swimming.", "trap_titles": ["Finding Dory", "Shark Tale"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-1891', '{"quote": "No, I am your father.", "trap_titles": ["Star Wars", "Return of the Jedi"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-694', '{"quote": "Here''s Johnny!", "trap_titles": ["Psycho", "Misery"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-9390', '{"quote": "Show me the money!", "trap_titles": ["Wall Street", "Moneyball"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-1885', '{"quote": "Wax on, wax off.", "trap_titles": ["The Karate Kid Part II", "Kung Fu Panda"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-744', '{"quote": "I feel the need... the need for speed!", "trap_titles": ["Days of Thunder", "Top Gun: Maverick"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-88', '{"quote": "Nobody puts Baby in a corner.", "trap_titles": ["Footloose", "Grease"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-1271', '{"quote": "This is Sparta!", "trap_titles": ["Troy", "Gladiator"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-70160', '{"quote": "I volunteer as tribute!", "trap_titles": ["The Hunger Games: Catching Fire", "Divergent"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-671', '{"quote": "Yer a wizard, Harry.", "trap_titles": ["Harry Potter and the Chamber of Secrets", "Fantastic Beasts and Where to Find Them"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-120', '{"quote": "You shall not pass!", "trap_titles": ["The Lord of the Rings: The Two Towers", "The Hobbit: An Unexpected Journey"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-105', '{"quote": "Roads? Where we''re going, we don''t need roads.", "trap_titles": ["Back to the Future Part II", "The Terminator"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-118340', '{"quote": "I am Groot.", "trap_titles": ["Guardians of the Galaxy Vol. 2", "The Avengers"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-1726', '{"quote": "I am Iron Man.", "trap_titles": ["Avengers: Endgame", "Iron Man 2"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-557', '{"quote": "With great power comes great responsibility.", "trap_titles": ["The Amazing Spider-Man", "Spider-Man: No Way Home"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-284054', '{"quote": "Wakanda forever!", "trap_titles": ["Avengers: Infinity War", "Black Panther: Wakanda Forever"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-771', '{"quote": "Keep the change, ya filthy animal.", "trap_titles": ["Home Alone 2: Lost in New York", "Goodfellas"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-10625', '{"quote": "On Wednesdays we wear pink.", "trap_titles": ["Clueless", "Legally Blonde"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-329', '{"quote": "Life finds a way.", "trap_titles": ["The Lost World: Jurassic Park", "Jurassic World"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-278', '{"quote": "Get busy living, or get busy dying.", "trap_titles": ["The Green Mile", "Dead Man Walking"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-268', '{"quote": "I''m Batman.", "trap_titles": ["Batman Begins", "The Dark Knight"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'tv-1399', '{"quote": "Winter is coming.", "trap_titles": ["House of the Dragon", "The Lord of the Rings: The Two Towers"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'tv-1668', '{"quote": "How you doin''?", "trap_titles": ["How I Met Your Mother", "Seinfeld"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'tv-456', '{"quote": "D''oh!", "trap_titles": ["Family Guy", "Futurama"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'tv-2316', '{"quote": "That''s what she said.", "trap_titles": ["Parks and Recreation", "Brooklyn Nine-Nine"]}'::jsonb, 1, 'quotes'),
  ('quote-match', 'movie-2493', '{"quote": "Hello. My name is Inigo Montoya. You killed my father. Prepare to die.", "trap_titles": ["Robin Hood: Prince of Thieves", "The Three Musketeers"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-98', '{"quote": "Are you not entertained?", "trap_titles": ["Braveheart", "Troy"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-197', '{"quote": "They may take our lives, but they''ll never take our freedom!", "trap_titles": ["Gladiator", "Rob Roy"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-240', '{"quote": "Keep your friends close, but your enemies closer.", "trap_titles": ["The Godfather", "Scarface"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-550', '{"quote": "The first rule of Fight Club is: you do not talk about Fight Club.", "trap_titles": ["Se7en", "The Matrix"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-603', '{"quote": "There is no spoon.", "trap_titles": ["The Matrix Reloaded", "Inception"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-807', '{"quote": "What''s in the box?", "trap_titles": ["Fight Club", "Zodiac"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-274', '{"quote": "I ate his liver with some fava beans and a nice Chianti.", "trap_titles": ["Hannibal", "Red Dragon"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-11528', '{"quote": "You''re killin'' me, Smalls!", "trap_titles": ["The Bad News Bears", "Little Giants"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-489', '{"quote": "How do you like them apples?", "trap_titles": ["Dead Poets Society", "The Departed"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-11036', '{"quote": "If you''re a bird, I''m a bird.", "trap_titles": ["A Walk to Remember", "Dear John"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-509', '{"quote": "I''m just a girl, standing in front of a boy, asking him to love her.", "trap_titles": ["Love Actually", "Four Weddings and a Funeral"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-28', '{"quote": "I love the smell of napalm in the morning.", "trap_titles": ["Platoon", "Full Metal Jacket"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-10673', '{"quote": "Greed, for lack of a better word, is good.", "trap_titles": ["The Wolf of Wall Street", "Boiler Room"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-813', '{"quote": "I am serious. And don''t call me Shirley.", "trap_titles": ["The Naked Gun", "Blazing Saddles"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-762', '{"quote": "It''s just a flesh wound.", "trap_titles": ["Monty Python''s Life of Brian", "The Princess Bride"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-8699', '{"quote": "I''m in a glass case of emotion!", "trap_titles": ["Talladega Nights: The Ballad of Ricky Bobby", "Step Brothers"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-10719', '{"quote": "You sit on a throne of lies.", "trap_titles": ["The Santa Clause", "A Christmas Story"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-8467', '{"quote": "So you''re telling me there''s a chance.", "trap_titles": ["The Mask", "Ace Ventura: Pet Detective"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-1892', '{"quote": "It''s a trap!", "trap_titles": ["The Empire Strikes Back", "Star Wars"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-106', '{"quote": "Get to the chopper!", "trap_titles": ["Commando", "Aliens"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-10650', '{"quote": "Go ahead, make my day.", "trap_titles": ["Dirty Harry", "Death Wish"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-10774', '{"quote": "I''m as mad as hell, and I''m not going to take this anymore!", "trap_titles": ["Broadcast News", "Nightcrawler"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-680', '{"quote": "They call it a Royale with cheese.", "trap_titles": ["Reservoir Dogs", "Jackie Brown"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-769', '{"quote": "As far back as I can remember, I always wanted to be a gangster.", "trap_titles": ["Casino", "The Godfather"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-11287', '{"quote": "There''s no crying in baseball!", "trap_titles": ["Field of Dreams", "Moneyball"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-9799', '{"quote": "I live my life a quarter mile at a time.", "trap_titles": ["2 Fast 2 Furious", "Days of Thunder"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-752', '{"quote": "Remember, remember, the fifth of November.", "trap_titles": ["Watchmen", "Sherlock Holmes"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-12445', '{"quote": "After all this time? Always.", "trap_titles": ["Harry Potter and the Half-Blood Prince", "Harry Potter and the Sorcerer''s Stone"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-350', '{"quote": "Florals? For spring? Groundbreaking.", "trap_titles": ["Confessions of a Shopaholic", "Ugly Betty"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-8835', '{"quote": "What, like it''s hard?", "trap_titles": ["Clueless", "Mean Girls"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-12133', '{"quote": "Did we just become best friends?", "trap_titles": ["Talladega Nights: The Ballad of Ricky Bobby", "Anchorman: The Legend of Ron Burgundy"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-525', '{"quote": "We''re on a mission from God.", "trap_titles": ["National Lampoon''s Animal House", "Wayne''s World"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-115', '{"quote": "The Dude abides.", "trap_titles": ["Fargo", "No Country for Old Men"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-438631', '{"quote": "Fear is the mind-killer.", "trap_titles": ["Dune: Part Two", "Blade Runner 2049"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-78', '{"quote": "I''ve seen things you people wouldn''t believe.", "trap_titles": ["Blade Runner 2049", "Total Recall"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-109445', '{"quote": "Some people are worth melting for.", "trap_titles": ["Frozen II", "Tangled"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-808', '{"quote": "Ogres are like onions.", "trap_titles": ["Shrek 2", "Monsters, Inc."]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-9806', '{"quote": "No capes!", "trap_titles": ["Incredibles 2", "Megamind"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-8681', '{"quote": "But what I do have are a very particular set of skills.", "trap_titles": ["John Wick", "Taken 2"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'tv-1396', '{"quote": "I am the one who knocks!", "trap_titles": ["Better Call Saul", "Ozark"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'tv-82856', '{"quote": "This is the way.", "trap_titles": ["The Book of Boba Fett", "Star Wars: The Force Awakens"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-22', '{"quote": "Why is the rum gone?", "trap_titles": ["Pirates of the Caribbean: Dead Man''s Chest", "Hook"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-24428', '{"quote": "That''s my secret, Captain: I''m always angry.", "trap_titles": ["Avengers: Age of Ultron", "The Incredible Hulk"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-299536', '{"quote": "Mr. Stark, I don''t feel so good.", "trap_titles": ["Avengers: Endgame", "Spider-Man: Homecoming"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-284053', '{"quote": "He''s a friend from work!", "trap_titles": ["The Avengers", "Thor: The Dark World"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-4232', '{"quote": "Do you like scary movies?", "trap_titles": ["I Know What You Did Last Summer", "Halloween"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-9340', '{"quote": "Goonies never say die!", "trap_titles": ["Stand by Me", "E.T. the Extra-Terrestrial"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-9377', '{"quote": "Bueller? Bueller?", "trap_titles": ["The Breakfast Club", "Sixteen Candles"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-1366', '{"quote": "Yo, Adrian!", "trap_titles": ["Rocky II", "Creed"]}'::jsonb, 2, 'quotes'),
  ('quote-match', 'movie-7345', '{"quote": "I drink your milkshake!", "trap_titles": ["No Country for Old Men", "Boogie Nights"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-829', '{"quote": "Forget it, Jake. It''s Chinatown.", "trap_titles": ["L.A. Confidential", "The Two Jakes"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-968', '{"quote": "Attica! Attica!", "trap_titles": ["Serpico", "The Taking of Pelham One Two Three"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-860', '{"quote": "Shall we play a game?", "trap_titles": ["Tron", "The Net"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-861', '{"quote": "Consider that a divorce.", "trap_titles": ["True Lies", "Terminator 2: Judgment Day"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-140607', '{"quote": "Chewie, we''re home.", "trap_titles": ["Star Wars: The Last Jedi", "Rogue One: A Star Wars Story"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-2898', '{"quote": "You make me want to be a better man.", "trap_titles": ["Jerry Maguire", "Good Will Hunting"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-583', '{"quote": "He''s not the Messiah. He''s a very naughty boy!", "trap_titles": ["Monty Python and the Holy Grail", "History of the World: Part I"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-9718', '{"quote": "Shake and bake!", "trap_titles": ["Days of Thunder", "Step Brothers"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-11635', '{"quote": "You''re my boy, Blue!", "trap_titles": ["Step Brothers", "National Lampoon''s Animal House"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-8469', '{"quote": "Toga! Toga!", "trap_titles": ["Old School", "Revenge of the Nerds"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-2028', '{"quote": "I gave her my heart, and she gave me a pen.", "trap_titles": ["The Breakfast Club", "Sixteen Candles"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-6977', '{"quote": "Call it, friendo.", "trap_titles": ["There Will Be Blood", "Fargo"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-17473', '{"quote": "Oh hi, Mark.", "trap_titles": ["The Disaster Artist", "Birdemic: Shock and Terror"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-766', '{"quote": "This is my boomstick!", "trap_titles": ["Evil Dead II", "The Evil Dead"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-283995', '{"quote": "I''m Mary Poppins, y''all!", "trap_titles": ["Guardians of the Galaxy", "Thor: Ragnarok"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-100402', '{"quote": "On your left.", "trap_titles": ["Captain America: The First Avenger", "Avengers: Endgame"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-284052', '{"quote": "Dormammu, I''ve come to bargain.", "trap_titles": ["Doctor Strange in the Multiverse of Madness", "Thor: Ragnarok"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-1771', '{"quote": "I can do this all day.", "trap_titles": ["Captain America: Civil War", "Avengers: Endgame"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-27205', '{"quote": "You mustn''t be afraid to dream a little bigger, darling.", "trap_titles": ["Interstellar", "Shutter Island"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-122', '{"quote": "My friends, you bow to no one.", "trap_titles": ["The Lord of the Rings: The Two Towers", "The Lord of the Rings: The Fellowship of the Ring"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-1893', '{"quote": "Now this is podracing!", "trap_titles": ["Star Wars: Episode II – Attack of the Clones", "Star Wars: Episode III – Revenge of the Sith"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-9708', '{"quote": "Not the bees!", "trap_titles": ["Midsommar", "Face/Off"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-424', '{"quote": "Whoever saves one life, saves the world entire.", "trap_titles": ["The Pianist", "Life Is Beautiful"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-747', '{"quote": "You''ve got red on you.", "trap_titles": ["Hot Fuzz", "Zombieland"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'tv-66732', '{"quote": "Friends don''t lie.", "trap_titles": ["It", "The Goonies"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-251', '{"quote": "Ditto.", "trap_titles": ["Dirty Dancing", "The Bodyguard"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-620', '{"quote": "He slimed me.", "trap_titles": ["Ghostbusters II", "Beetlejuice"]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-1880', '{"quote": "Wolverines!", "trap_titles": ["Rambo: First Blood Part II", "Invasion U.S.A."]}'::jsonb, 3, 'quotes'),
  ('quote-match', 'movie-1648', '{"quote": "Be excellent to each other.", "trap_titles": ["Wayne''s World", "Fast Times at Ridgemont High"]}'::jsonb, 3, 'quotes'),
  ('emoji', 'movie-597', '{"emoji": "🚢🧊💑🌊", "decoys": ["Poseidon", "The Perfect Storm"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-578', '{"emoji": "🦈🏖️😱🚤", "decoys": ["The Meg", "Deep Blue Sea"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-329', '{"emoji": "🦖🏝️🔬🎢", "decoys": ["King Kong", "Godzilla"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-630', '{"emoji": "🌪️👠🦁🧙", "decoys": ["Alice in Wonderland", "Oz the Great and Powerful"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-12', '{"emoji": "🐠🌊🔍👨‍👦", "decoys": ["Shark Tale", "The Little Mermaid"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-8587', '{"emoji": "🦁👑🐗🌅", "decoys": ["Madagascar", "The Jungle Book"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-601', '{"emoji": "👽🚲🌕☎️", "decoys": ["Close Encounters of the Third Kind", "Flight of the Navigator"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-771', '{"emoji": "👦🏠🎄😱", "decoys": ["Elf", "The Santa Clause"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-603', '{"emoji": "💊🕶️🤖💻", "decoys": ["Tron", "Inception"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-408', '{"emoji": "🍎👸😴⛏️", "decoys": ["Sleeping Beauty", "Enchanted"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-109445', '{"emoji": "❄️👭⛄🏰", "decoys": ["Tangled", "Ice Age"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-14160', '{"emoji": "🎈🏠👴🐦", "decoys": ["Around the World in 80 Days", "Cloudy with a Chance of Meatballs"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-2062', '{"emoji": "🐀👨‍🍳🍲", "decoys": ["Chef", "Julie & Julia"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-694', '{"emoji": "🏨❄️🪓👨‍👩‍👦", "decoys": ["Misery", "Psycho"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-1366', '{"emoji": "🥊🏃🥩🏆", "decoys": ["Creed", "Raging Bull"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-13', '{"emoji": "🏃🍫🦐🏓", "decoys": ["Rain Man", "Big"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-8358', '{"emoji": "✈️🏝️🏐📦", "decoys": ["Life of Pi", "The Martian"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-87827', '{"emoji": "🚢🐯🛶🌊", "decoys": ["Cast Away", "The Jungle Book"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-286217', '{"emoji": "👨‍🚀🥔🔴🚀", "decoys": ["Gravity", "Interstellar"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-49047', '{"emoji": "👩‍🚀💥🛰️🌍", "decoys": ["The Martian", "Apollo 13"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-568', '{"emoji": "🚀🌕⚠️🌍", "decoys": ["First Man", "Gravity"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-254', '{"emoji": "🦍🏙️✈️👱‍♀️", "decoys": ["Godzilla", "Mighty Joe Young"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-124905', '{"emoji": "🦎☢️🏙️💥", "decoys": ["King Kong", "Pacific Rim"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-620', '{"emoji": "👻🚫🏙️🔫", "decoys": ["Beetlejuice", "Casper"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-105', '{"emoji": "⏰🚗⚡👨‍🔬", "decoys": ["The Time Machine", "Bill & Ted''s Excellent Adventure"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-671', '{"emoji": "⚡👓🏰🧙", "decoys": ["The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", "Percy Jackson & the Olympians: The Lightning Thief"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-120', '{"emoji": "💍🌋🧙‍♂️🗡️", "decoys": ["The Hobbit: An Unexpected Journey", "Willow"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-11', '{"emoji": "🚀⚔️🤖👸", "decoys": ["Star Trek", "Guardians of the Galaxy"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-557', '{"emoji": "🕷️👦🕸️🏙️", "decoys": ["Venom", "Ant-Man"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-155', '{"emoji": "🦇🃏💥🚔", "decoys": ["Batman Begins", "Joker"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-1726', '{"emoji": "💰🛠️🤖✈️", "decoys": ["RoboCop", "Transformers"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-24428', '{"emoji": "🦸👽🏙️💥", "decoys": ["Justice League", "X-Men"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-297762', '{"emoji": "👸🗡️⚔️🕊️", "decoys": ["Captain Marvel", "Justice League"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-284054', '{"emoji": "🐆👑🌍💎", "decoys": ["Captain Marvel", "Blade"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-862', '{"emoji": "🤠🚀🧸👦", "decoys": ["The Lego Movie", "Small Soldiers"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-808', '{"emoji": "👹🐴👸🏰", "decoys": ["Beauty and the Beast", "Brave"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-10020', '{"emoji": "🥀👸🏰🕯️", "decoys": ["Cinderella", "Shrek"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-11224', '{"emoji": "👠🎃👸🕛", "decoys": ["Snow White and the Seven Dwarfs", "Ella Enchanted"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-812', '{"emoji": "🧞💡🐒🕌", "decoys": ["Prince of Persia: The Sands of Time", "The Thief of Bagdad"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-277834', '{"emoji": "🌊⛵🐔🗿", "decoys": ["Lilo & Stitch", "Pocahontas"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-10895', '{"emoji": "👦👃🧚🐋", "decoys": ["Peter Pan", "Dumbo"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-10693', '{"emoji": "🧚🏴‍☠️👦⏰", "decoys": ["Hook", "Tinker Bell"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-10144', '{"emoji": "🧜‍♀️🦀👑🎶", "decoys": ["Moana", "Aquamarine"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-11360', '{"emoji": "🐘👂🎪✨", "decoys": ["The Jungle Book", "Bambi"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-118', '{"emoji": "🍫🎫🏭👦", "decoys": ["Wonka", "Matilda"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-10830', '{"emoji": "👧📚✨🏫", "decoys": ["The Witches", "Nanny McPhee"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-106646', '{"emoji": "💰📈💊🛥️", "decoys": ["The Big Short", "Wall Street"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-37799', '{"emoji": "💻👥⚖️🎓", "decoys": ["Steve Jobs", "Jobs"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-27205', '{"emoji": "😴💭🌀🏢", "decoys": ["The Matrix", "Shutter Island"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-157336', '{"emoji": "🚀🌽⏳🕳️", "decoys": ["Gravity", "Arrival"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-329865', '{"emoji": "🛸👩‍🏫✍️⏳", "decoys": ["Contact", "Interstellar"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-244786', '{"emoji": "🥁😤👨‍🏫🏆", "decoys": ["Drumline", "La La Land"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-313369', '{"emoji": "💃🎹🌆💔", "decoys": ["A Star Is Born", "500 Days of Summer"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-621', '{"emoji": "🕺💇‍♀️🚗🎶", "decoys": ["Hairspray", "Dirty Dancing"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-88', '{"emoji": "💃🏨🍉👫", "decoys": ["Footloose", "Grease"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-1788', '{"emoji": "🕺🚫⛪🏘️", "decoys": ["Flashdance", "Grease"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-11631', '{"emoji": "👰🏝️👨👨👨", "decoys": ["My Big Fat Greek Wedding", "Letters to Juliet"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-15121', '{"emoji": "⛰️🎶👗👨‍👩‍👧‍👦", "decoys": ["Mary Poppins", "Annie"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-433', '{"emoji": "☂️👩✨🧒", "decoys": ["Nanny McPhee", "The Sound of Music"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-238', '{"emoji": "🤵💼🔫🐎", "decoys": ["Goodfellas", "Scarface"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-769', '{"emoji": "🔫🍝💰🚁", "decoys": ["The Godfather", "Casino"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-111', '{"emoji": "💵🔫🌴😤", "decoys": ["The Godfather", "Carlito''s Way"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-680', '{"emoji": "💼🕺💉🍔", "decoys": ["Reservoir Dogs", "Kill Bill: Vol. 1"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-24', '{"emoji": "👰🗡️💛⚔️", "decoys": ["Pulp Fiction", "John Wick"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-245891', '{"emoji": "🐶⚰️🔫😡", "decoys": ["Taken", "The Equalizer"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-8681', '{"emoji": "👨👧✈️📞🔫", "decoys": ["John Wick", "Ransom"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-562', '{"emoji": "🏢🎄🔫🦶", "decoys": ["Lethal Weapon", "Speed"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-1637', '{"emoji": "🚌💣⏱️", "decoys": ["Die Hard", "The Fast and the Furious"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-9799', '{"emoji": "🚗🏁🚓💨", "decoys": ["Need for Speed", "Gone in 60 Seconds"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-76341', '{"emoji": "🚗🔥🏜️💀", "decoys": ["Waterworld", "The Book of Eli"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-438631', '{"emoji": "🏜️🐛👑✨", "decoys": ["Mad Max: Fury Road", "John Carter"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-19995', '{"emoji": "🔵🌳👽🚁", "decoys": ["Guardians of the Galaxy", "Pocahontas"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-10681', '{"emoji": "🤖🌱🚀💕", "decoys": ["Big Hero 6", "Short Circuit"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-177572', '{"emoji": "🤖❤️👦🦸", "decoys": ["The Iron Giant", "Astro Boy"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-10386', '{"emoji": "🤖👦🌲☄️", "decoys": ["Big Hero 6", "Transformers"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-585', '{"emoji": "👹🚪😱👧", "decoys": ["Hotel Transylvania", "Monsters University"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-150540', '{"emoji": "😀😢😡🧠", "decoys": ["Soul", "The Emoji Movie"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-354912', '{"emoji": "💀🎸👦🌼", "decoys": ["The Book of Life", "Encanto"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-568124', '{"emoji": "🏠✨🕯️👨‍👩‍👧‍👦", "decoys": ["Coco", "Luca"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-9806', '{"emoji": "🦸👨‍👩‍👧‍👦🏝️🤖", "decoys": ["Sky High", "Fantastic Four"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-20352', '{"emoji": "😈👧👧👧🌕", "decoys": ["Megamind", "Minions"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-8871', '{"emoji": "😾💚🎄🎁", "decoys": ["Elf", "The Nightmare Before Christmas"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-10719', '{"emoji": "🧝🎄🗽😄", "decoys": ["The Santa Clause", "Fred Claus"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-9479', '{"emoji": "💀🎃🎄🎅", "decoys": ["Corpse Bride", "Coraline"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-14836', '{"emoji": "👧🚪🧵👀", "decoys": ["The Nightmare Before Christmas", "ParaNorman"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-539', '{"emoji": "🚿🔪🏨👩", "decoys": ["Scream", "The Shining"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-4232', '{"emoji": "📞🔪🎭😱", "decoys": ["Halloween", "I Know What You Did Last Summer"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-274', '{"emoji": "👮‍♀️🧠🍽️🦋", "decoys": ["Se7en", "Hannibal"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-807', '{"emoji": "📦🕵️🌧️😱", "decoys": ["Zodiac", "The Silence of the Lambs"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-745', '{"emoji": "👦👀👻😨", "decoys": ["The Others", "Ghost"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-251', '{"emoji": "💑🏺👻💔", "decoys": ["The Sixth Sense", "City of Angels"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-37165', '{"emoji": "😀📺🎥⛵🚪", "decoys": ["EDtv", "Pleasantville"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-137', '{"emoji": "⏰🔁😩❄️", "decoys": ["Palm Springs", "Edge of Tomorrow"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-137113', '{"emoji": "👽🔫🔁💀", "decoys": ["Groundhog Day", "Source Code"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-70160', '{"emoji": "🏹👧📺⚔️", "decoys": ["Divergent", "The Maze Runner"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-198663', '{"emoji": "🏃🧱🌀👦", "decoys": ["The Hunger Games", "Divergent"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-8966', '{"emoji": "🧛💑🐺🌲", "decoys": ["Interview with the Vampire", "Vampire Academy"]}'::jsonb, 1, 'emoji'),
  ('emoji', 'movie-11036', '{"emoji": "💑🌧️⛵👴👵", "decoys": ["A Walk to Remember", "Dear John"]}'::jsonb, 2, 'emoji'),
  ('emoji', 'movie-12405', '{"emoji": "👦📺💰❓", "decoys": ["Lion", "Quiz Show"]}'::jsonb, 3, 'emoji'),
  ('emoji', 'movie-98', '{"emoji": "⚔️🏟️👑💀", "decoys": ["Troy", "300"]}'::jsonb, 2, 'emoji'),
  ('sequel-or-fake', null, '{"title": "Savage Sam", "year": 1963, "real": true, "anchor": "Old Yeller", "reveal": "Disney really made a sequel about Old Yeller''s son, released six years after they shot the dog."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Look What''s Happened to Rosemary''s Baby", "year": 1976, "real": true, "anchor": "Rosemary''s Baby", "reveal": "ABC aired this TV sequel with Patty Duke taking over the Mia Farrow role and the baby now a grown man."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Oliver''s Story", "year": 1978, "real": true, "anchor": "Love Story", "reveal": "Ryan O''Neal returned for a sequel about Oliver dating again after Jenny''s death, and it flopped."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Bad News Bears Go to Japan", "year": 1978, "real": true, "anchor": "The Bad News Bears", "reveal": "The third Bears film sends the team to Tokyo with Tony Curtis as their hustler promoter."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Butch and Sundance: The Early Days", "year": 1979, "real": true, "anchor": "Butch Cassidy and the Sundance Kid", "reveal": "A prequel with Tom Berenger and William Katt in the Newman and Redford roles."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "More American Graffiti", "year": 1979, "real": true, "anchor": "American Graffiti", "reveal": "The sequel scatters the cast across Vietnam, drag strips, and Haight-Ashbury, with storylines shot in different aspect ratios."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Grease 2", "year": 1982, "real": true, "anchor": "Grease", "reveal": "Michelle Pfeiffer''s first lead role; almost nobody from the original returned except Frenchy and the teachers."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Trail of the Pink Panther", "year": 1982, "real": true, "anchor": "The Pink Panther", "reveal": "Released two years after Peter Sellers died, it stars him anyway, assembled from outtakes."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Sting II", "year": 1983, "real": true, "anchor": "The Sting", "reveal": "Jackie Gleason and Mac Davis replaced Newman and Redford, and it still landed an Oscar nomination for its score."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Staying Alive", "year": 1983, "real": true, "anchor": "Saturday Night Fever", "reveal": "The Saturday Night Fever sequel was written and directed by Sylvester Stallone."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Smokey and the Bandit Part 3", "year": 1983, "real": true, "anchor": "Smokey and the Bandit", "reveal": "Burt Reynolds appears only in a cameo; an early cut reportedly had Jackie Gleason playing both Smokey and the Bandit."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Return to Oz", "year": 1985, "real": true, "anchor": "The Wizard of Oz", "reveal": "Disney''s sequel opens with Dorothy being sent for electroshock therapy."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Parent Trap II", "year": 1986, "real": true, "anchor": "The Parent Trap", "reveal": "Hayley Mills played both twins again in a TV sequel 25 years after the original."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Teen Wolf Too", "year": 1987, "real": true, "anchor": "Teen Wolf", "reveal": "Jason Bateman replaced Michael J. Fox as the wolf''s cousin, who boxes instead of playing basketball."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Caddyshack II", "year": 1988, "real": true, "anchor": "Caddyshack", "reveal": "Jackie Mason stepped in for Rodney Dangerfield; Chevy Chase and the gopher were the main returnees."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Splash, Too", "year": 1988, "real": true, "anchor": "Splash", "reveal": "Disney made a TV sequel with a different actor in every role, including the mermaid."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Two Jakes", "year": 1990, "real": true, "anchor": "Chinatown", "reveal": "Jack Nicholson directed himself in the Chinatown sequel."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Omen IV: The Awakening", "year": 1991, "real": true, "anchor": "The Omen", "reveal": "The fourth Omen is a TV movie about Damien''s daughter."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Weekend at Bernie''s II", "year": 1993, "real": true, "anchor": "Weekend at Bernie''s", "reveal": "Voodoo partially reanimates the corpse, which can only walk when calypso music plays."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Birds II: Land''s End", "year": 1994, "real": true, "anchor": "The Birds", "reveal": "The made-for-TV Hitchcock sequel''s director took his name off it and is credited as Alan Smithee."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The NeverEnding Story III", "year": 1994, "real": true, "anchor": "The NeverEnding Story", "reveal": "A young Jack Black plays the bully who leads a gang called the Nasties."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Blues Brothers 2000", "year": 1998, "real": true, "anchor": "The Blues Brothers", "reveal": "John Goodman fills the John Belushi slot and the band adds a ten-year-old."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Rage: Carrie 2", "year": 1999, "real": true, "anchor": "Carrie", "reveal": "Amy Irving returned as Sue Snell, the only link to the 1976 original, 23 years later."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Book of Shadows: Blair Witch 2", "year": 2000, "real": true, "anchor": "The Blair Witch Project", "reveal": "The studio recut it so heavily that its director, a respected documentarian, disowned the result."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Cruel Intentions 2", "year": 2000, "real": true, "anchor": "Cruel Intentions", "reveal": "It began as a failed TV prequel pilot and was stitched into a direct-to-video movie."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "American Psycho 2", "year": 2002, "real": true, "anchor": "American Psycho", "reveal": "Mila Kunis plays a student who killed Patrick Bateman as a child, a premise she has since said she regrets."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Home Alone 4: Taking Back the House", "year": 2002, "real": true, "anchor": "Home Alone", "reveal": "A TV movie that recast every single role, including Kevin."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Christmas Vacation 2: Cousin Eddie''s Island Adventure", "year": 2003, "real": true, "anchor": "National Lampoon''s Christmas Vacation", "reveal": "A TV sequel in which Randy Quaid''s Cousin Eddie is the lead and the Griswolds barely appear."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Dumb and Dumberer: When Harry Met Lloyd", "year": 2003, "real": true, "anchor": "Dumb and Dumber", "reveal": "A prequel with new actors as teenage Harry and Lloyd; the Farrelly brothers had nothing to do with it."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Dirty Dancing: Havana Nights", "year": 2004, "real": true, "anchor": "Dirty Dancing", "reveal": "A 1958 Cuba retelling in which Patrick Swayze cameos as a dance instructor."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Carlito''s Way: Rise to Power", "year": 2005, "real": true, "anchor": "Carlito''s Way", "reveal": "A direct-to-video prequel with Jay Hernandez in the Al Pacino role."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Son of the Mask", "year": 2005, "real": true, "anchor": "The Mask", "reveal": "Jamie Kennedy replaced Jim Carrey and a baby gets the mask''s powers."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Single White Female 2: The Psycho", "year": 2005, "real": true, "anchor": "Single White Female", "reveal": "The subtitle is literally The Psycho, and it went straight to video 13 years later with no returning cast."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Net 2.0", "year": 2006, "real": true, "anchor": "The Net", "reveal": "The straight-to-DVD sequel was directed by the son of the man who directed the original."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Road House 2: Last Call", "year": 2006, "real": true, "anchor": "Road House", "reveal": "The straight-to-DVD sequel arrived 17 years later with none of the original cast."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Bachelor Party 2: The Last Temptation", "year": 2008, "real": true, "anchor": "Bachelor Party", "reveal": "The Tom Hanks comedy got an unrated direct-to-DVD sequel 24 years later."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "S. Darko", "year": 2009, "real": true, "anchor": "Donnie Darko", "reveal": "A sequel following Donnie''s little sister Samantha; Richard Kelly had no involvement."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Ace Ventura Jr.: Pet Detective", "year": 2009, "real": true, "anchor": "Ace Ventura: Pet Detective", "reveal": "A kids'' TV movie about Ace''s son; Jim Carrey is nowhere in it."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Legally Blondes", "year": 2009, "real": true, "anchor": "Legally Blonde", "reveal": "A direct-to-DVD spinoff about Elle''s British twin cousins, produced by Reese Witherspoon, who does not appear."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Mean Girls 2", "year": 2011, "real": true, "anchor": "Mean Girls", "reveal": "A made-for-TV sequel whose only returning character is Principal Duvall."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "A Christmas Story 2", "year": 2012, "real": true, "anchor": "A Christmas Story", "reveal": "An official direct-to-video sequel with Daniel Stern as the Old Man."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Jarhead 2: Field of Fire", "year": 2014, "real": true, "anchor": "Jarhead", "reveal": "The Sam Mendes war drama got a straight-to-video action sequel with an unrelated cast, then two more."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Jingle All the Way 2", "year": 2014, "real": true, "anchor": "Jingle All the Way", "reveal": "Larry the Cable Guy took over the Schwarzenegger role in a WWE Studios production."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Kindergarten Cop 2", "year": 2016, "real": true, "anchor": "Kindergarten Cop", "reveal": "Dolph Lundgren teaches the kindergarten this time, direct to video."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Backdraft 2", "year": 2019, "real": true, "anchor": "Backdraft", "reveal": "It arrived 28 years later, straight to video, with William Baldwin back."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Ghost 2: Unfinished Business", "year": null, "real": false, "anchor": "Ghost", "reveal": "Ghost never got a sequel; the subtitle borrows the film''s own premise, which is exactly what a real DTV sequel would do."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Top Gun: Afterburner", "year": null, "real": false, "anchor": "Top Gun", "reveal": "The only real sequel is Maverick; Afterburner is just the right amount of jet jargon."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Speed 3: Flatline", "year": null, "real": false, "anchor": "Speed", "reveal": "The franchise stopped at Cruise Control; a Speed 3 exists only as a Father Ted joke."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Con Air 2: Final Descent", "year": null, "real": false, "anchor": "Con Air", "reveal": "Con Air never got a sequel, though every part of this title sounds like it did."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Air Force One: Retaliation", "year": null, "real": false, "anchor": "Air Force One", "reveal": "No sequel exists; the closest real title is the unrelated 2024 movie Air Force One Down."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Fugitive: Dead Run", "year": null, "real": false, "anchor": "The Fugitive", "reveal": "The real follow-up is U.S. Marshals, which dropped both Harrison Ford and the title."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Panic Room 2: Home Invasion", "year": null, "real": false, "anchor": "Panic Room", "reveal": "The Fincher film has no sequel; the subtitle is the entire genre."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Fatal Attraction 2: Obsession", "year": null, "real": false, "anchor": "Fatal Attraction", "reveal": "No film sequel exists, only a 2023 TV series."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Hand That Rocks the Cradle 2: A Family Affair", "year": null, "real": false, "anchor": "The Hand That Rocks the Cradle", "reveal": "No sequel exists; the title copies the real Single White Female 2 formula exactly."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Flashdance 2: Steel City Nights", "year": null, "real": false, "anchor": "Flashdance", "reveal": "Flashdance has no sequel; Steel City is Pittsburgh, which is the kind of homework a DTV subtitle does."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Footloose: The Next Step", "year": null, "real": false, "anchor": "Footloose", "reveal": "No sequel exists, just a 2011 remake."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Coyote Ugly 2: Last Dance", "year": null, "real": false, "anchor": "Coyote Ugly", "reveal": "A sequel was reported to be in development and never appeared."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Bodyguard 2: Never Let Go", "year": null, "real": false, "anchor": "The Bodyguard", "reveal": "The Costner film has no sequel; unrelated Asian action movies have used the base title."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Pretty Woman: Ever After", "year": null, "real": false, "anchor": "Pretty Woman", "reveal": "No sequel exists; Garry Marshall reunited the leads in Runaway Bride instead."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Sweet Home Alabama 2: Southern Vows", "year": null, "real": false, "anchor": "Sweet Home Alabama", "reveal": "No sequel was ever made despite years of sequel talk."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Clueless 2: Back in Session", "year": null, "real": false, "anchor": "Clueless", "reveal": "Clueless got a TV series and a musical, never a film sequel."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "10 Things I Hate About You Too", "year": null, "real": false, "anchor": "10 Things I Hate About You", "reveal": "The ''Too'' construction is stolen from Teen Wolf Too, which is real; this one is not."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "She''s All That 2: Prom Queen", "year": null, "real": false, "anchor": "She''s All That", "reveal": "The franchise''s only follow-up is the gender-swapped remake He''s All That."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Old School 2: Homecoming", "year": null, "real": false, "anchor": "Old School", "reveal": "A sequel was talked about for years and never made."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "EuroTrip 2: Winter Break", "year": null, "real": false, "anchor": "EuroTrip", "reveal": "EuroTrip flopped in theaters and thrived on DVD, exactly where a sequel would have lived; none exists."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Liar Liar 2: Truth Be Told", "year": null, "real": false, "anchor": "Liar Liar", "reveal": "Jim Carrey hits really did spawn Carrey-less DTV sequels, but Liar Liar was spared."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Mrs. Doubtfire 2: The Nanny Returns", "year": null, "real": false, "anchor": "Mrs. Doubtfire", "reveal": "A real sequel was in development before Robin Williams died; it never got this far."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Matilda 2: The New Girl", "year": null, "real": false, "anchor": "Matilda", "reveal": "Matilda''s only follow-up is the musical; no DTV sequel exists."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Homeward Bound III: Lost in the Rockies", "year": null, "real": false, "anchor": "Homeward Bound: The Incredible Journey", "reveal": "The series stopped at Lost in San Francisco; the third trip is invented."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Cool Runnings 2: Back on Ice", "year": null, "real": false, "anchor": "Cool Runnings", "reveal": "Disney never made one, despite making sequels to far smaller hits in that era."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Little Giants 2: Away Game", "year": null, "real": false, "anchor": "Little Giants", "reveal": "No sequel exists; Away Game is the standard kids-sports-sequel subtitle."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Rookie of the Year 2: The Big Leagues", "year": null, "real": false, "anchor": "Rookie of the Year", "reveal": "No sequel exists; the title just follows the real Sandlot sequel formula."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Varsity Blues 2: The Comeback", "year": null, "real": false, "anchor": "Varsity Blues", "reveal": "No sequel was ever made."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Sinister 3", "year": null, "real": false, "anchor": "Sinister", "reveal": "Sinister 2 is real; a third was discussed and never happened."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Arachnophobia 2: The Nest", "year": null, "real": false, "anchor": "Arachnophobia", "reveal": "The original has no sequel, only a long-rumored remake."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Scarface: The Beginning", "year": null, "real": false, "anchor": "Scarface", "reveal": "Carlito''s Way really got a DTV prequel exactly like this; Scarface did not."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Training Day 2: Graduation Day", "year": null, "real": false, "anchor": "Training Day", "reveal": "The follow-up was a 2017 CBS series, never a film."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Goonies: Return to Astoria", "year": null, "real": false, "anchor": "The Goonies", "reveal": "Decades of sequel rumors produced an NES game and nothing else."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Twister: Eye of the Storm", "year": null, "real": false, "anchor": "Twister", "reveal": "The real sequel waited 28 years and is called Twisters."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Poltergeist IV: The Reckoning", "year": null, "real": false, "anchor": "Poltergeist", "reveal": "The series stopped at III in 1988, plus a remake; a fourth exists only here."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Weird Science 2", "year": null, "real": false, "anchor": "Weird Science", "reveal": "It became a TV series instead; there is no film sequel."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Ferris Bueller''s Day Off 2", "year": null, "real": false, "anchor": "Ferris Bueller''s Day Off", "reveal": "No sequel exists; the closest thing is a Super Bowl ad Broderick did in character."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Turner & Hooch 2: New Tricks", "year": null, "real": false, "anchor": "Turner & Hooch", "reveal": "The follow-up was a 2021 Disney+ series; the dog never got a film sequel."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Pacifier 2: Basic Training", "year": null, "real": false, "anchor": "The Pacifier", "reveal": "No sequel exists; the Vin Diesel family comedy stayed a one-off."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Snow Dogs 2: Race to the Pole", "year": null, "real": false, "anchor": "Snow Dogs", "reveal": "Disney made sequels to much smaller hits, but not this one."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "My Girl 3", "year": null, "real": false, "anchor": "My Girl", "reveal": "My Girl 2 is real; the third one is not."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "Baby''s Day Out 2", "year": null, "real": false, "anchor": "Baby''s Day Out", "reveal": "A theatrical flop that thrived on video is exactly the profile that got sequels; this one didn''t."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Waterboy 2: Overtime", "year": null, "real": false, "anchor": "The Waterboy", "reveal": "Sandler never made one, though Happy Gilmore eventually got its real sequel."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "What Lies Beneath 2: Still Waters", "year": null, "real": false, "anchor": "What Lies Beneath", "reveal": "The Zemeckis thriller has no sequel; the subtitle is standard DTV water metaphor."}'::jsonb, 2, 'sequels'),
  ('sequel-or-fake', null, '{"title": "The Wedding Planner 2: The Honeymoon", "year": null, "real": false, "anchor": "The Wedding Planner", "reveal": "No sequel exists; Jennifer Lopez rom-coms never got the DTV treatment."}'::jsonb, 2, 'sequels'),
  ('screening', null, '{"q": "Who played Jack Dawson in Titanic (1997)?", "choices": ["Brad Pitt", "Leonardo DiCaprio", "Matt Damon", "Johnny Depp"], "answer": 1, "note": "DiCaprio wasn''t nominated for an Oscar for Titanic, despite the film winning 11."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played Tony Stark in Iron Man (2008)?", "choices": ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Jude Law"], "answer": 0, "note": "Downey improvised the final line, ''I am Iron Man.''"}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "What year did the first Star Wars movie hit theaters?", "choices": ["1975", "1979", "1977", "1981"], "answer": 2, "note": "It opened in just 32 theaters in the US."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "On Friends, what is the name of the gang''s favorite coffee shop?", "choices": ["Central Perk", "The Grind", "Cafe Nervosa", "MacLaren''s"], "answer": 0, "note": "Cafe Nervosa is Frasier''s spot; MacLaren''s is from How I Met Your Mother."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "On Breaking Bad, what subject does Walter White teach?", "choices": ["Physics", "Biology", "Math", "Chemistry"], "answer": 3, "note": "Creator Vince Gilligan pitched it as turning Mr. Chips into Scarface."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who voiced Buzz Lightyear in Toy Story (1995)?", "choices": ["Billy Crystal", "Tim Allen", "Tom Hanks", "John Goodman"], "answer": 1, "note": "Billy Crystal turned down Buzz, then took Mike Wazowski in Monsters, Inc."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "In Jaws, the shark terrorizes which fictional beach town?", "choices": ["Bodega Bay", "Cape Fear", "Amity Island", "Montauk Point"], "answer": 2, "note": "The malfunctioning mechanical shark was nicknamed Bruce."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "What year did Jurassic Park first open in theaters?", "choices": ["1991", "1993", "1995", "1997"], "answer": 1, "note": "Spielberg released Schindler''s List the same year."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "The Office (US) is set in which Pennsylvania city?", "choices": ["Scranton", "Pittsburgh", "Allentown", "Harrisburg"], "answer": 0, "note": "Dunder Mifflin''s building in the opening credits is a real Scranton office."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played Hermione Granger in the Harry Potter films?", "choices": ["Bonnie Wright", "Evanna Lynch", "Katie Leung", "Emma Watson"], "answer": 3, "note": "Watson was nine years old when she was cast."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "In The Lion King (1994), what is the name of Simba''s father?", "choices": ["Scar", "Mufasa", "Rafiki", "Zazu"], "answer": 1, "note": "James Earl Jones voiced Mufasa in both the 1994 and 2019 versions."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "''Winter is coming'' is the motto of which Game of Thrones house?", "choices": ["House Lannister", "House Targaryen", "House Stark", "House Baratheon"], "answer": 2, "note": "The Lannister sayings are ''Hear Me Roar'' and the unofficial one about debts."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played Neo in The Matrix (1999)?", "choices": ["Keanu Reeves", "Will Smith", "Johnny Depp", "Brad Pitt"], "answer": 0, "note": "Will Smith really did turn it down, choosing Wild Wild West instead."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Stranger Things takes place in which fictional Indiana town?", "choices": ["Derry", "Hawkins", "Riverdale", "Greendale"], "answer": 1, "note": "Derry is Stephen King''s cursed town from It."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Rocky (1976) is set in which American city?", "choices": ["Chicago", "New York", "Boston", "Philadelphia"], "answer": 3, "note": "Tourists still run the museum steps he trained on."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played the title role in Forrest Gump (1994)?", "choices": ["Robin Williams", "Kevin Costner", "Tom Hanks", "Bill Murray"], "answer": 2, "note": "Hanks won back-to-back Best Actor Oscars for Philadelphia and Forrest Gump."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "In Finding Nemo, what kind of fish is Nemo?", "choices": ["Angelfish", "Pufferfish", "Blue tang", "Clownfish"], "answer": 3, "note": "Dory the blue tang got her own movie 13 years later."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Squid Game comes from which country?", "choices": ["Japan", "South Korea", "Thailand", "China"], "answer": 1, "note": "Creator Hwang Dong-hyuk wrote the script more than a decade before Netflix bought it."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played Captain Jack Sparrow in Pirates of the Caribbean?", "choices": ["Orlando Bloom", "Heath Ledger", "Johnny Depp", "Russell Brand"], "answer": 2, "note": "Depp based the character partly on Rolling Stone Keith Richards, who later played Jack''s father."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "In Frozen, what is the name of Elsa''s younger sister?", "choices": ["Anna", "Elena", "Moana", "Ariel"], "answer": 0, "note": "''Let It Go'' was written in a single day by Kristen Anderson-Lopez and Robert Lopez."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played Katniss Everdeen in The Hunger Games?", "choices": ["Shailene Woodley", "Emma Stone", "Kristen Stewart", "Jennifer Lawrence"], "answer": 3, "note": "Lawrence was 21 when the first film shot; Katniss is 16 in the book."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "In E.T., what does the alien famously want to do?", "choices": ["Go home... er, phone home", "Find his ship", "Eat pizza", "Meet the president"], "answer": 0, "note": "Those Reese''s Pieces? M&M''s turned the product placement down first."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played the Joker in The Dark Knight (2008)?", "choices": ["Jared Leto", "Heath Ledger", "Joaquin Phoenix", "Jack Nicholson"], "answer": 1, "note": "Ledger won a posthumous Oscar, the first acting win for a comic-book movie."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "What year does Marty McFly leave in Back to the Future?", "choices": ["1975", "1982", "1985", "1989"], "answer": 2, "note": "He travels back to 1955, the year his parents met."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played Danny Zuko in Grease (1978)?", "choices": ["Patrick Swayze", "Richard Gere", "Kevin Bacon", "John Travolta"], "answer": 3, "note": "Richard Gere had played Danny in the London stage production."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "What kind of creature is Shrek?", "choices": ["A troll", "An ogre", "A goblin", "A giant"], "answer": 1, "note": "Shrek won the first ever Oscar for Best Animated Feature."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "''Who ya gonna call?'' sold which 1984 movie?", "choices": ["Gremlins", "Beetlejuice", "Ghostbusters", "Poltergeist"], "answer": 2, "note": "Ray Parker Jr.''s theme song spent three weeks at number one."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "The Queen''s Gambit is about a prodigy in which game?", "choices": ["Poker", "Chess", "Bridge", "Scrabble"], "answer": 1, "note": "Chess set sales spiked worldwide after the show dropped in 2020."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "How many people are in Danny Ocean''s crew in Ocean''s Eleven (2001)?", "choices": ["Ten", "Eleven", "Twelve", "Thirteen"], "answer": 1, "note": "The sequels kept counting: Ocean''s Twelve, then Ocean''s Thirteen."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who plays the wisecracking mercenary in Deadpool (2016)?", "choices": ["Chris Pratt", "Ryan Gosling", "Hugh Jackman", "Ryan Reynolds"], "answer": 3, "note": "Reynolds first played a very different Deadpool in 2009''s X-Men Origins: Wolverine."}'::jsonb, 1, 'trivia'),
  ('screening', null, '{"q": "Who played mob boss Tony Soprano on The Sopranos?", "choices": ["James Gandolfini", "Al Pacino", "Ray Liotta", "Michael Imperioli"], "answer": 0, "note": "Gandolfini was a virtual unknown when HBO cast him in 1999."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What year was The Godfather released?", "choices": ["1969", "1972", "1974", "1976"], "answer": 1, "note": "Its sequel arrived just two years later and also won Best Picture."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "How many Infinity Stones does Thanos collect in Avengers: Infinity War?", "choices": ["Four", "Five", "Six", "Seven"], "answer": 2, "note": "Space, Mind, Reality, Power, Time, and Soul."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played the Dude in The Big Lebowski (1998)?", "choices": ["Nicolas Cage", "John Goodman", "Jeff Bridges", "Sam Elliott"], "answer": 2, "note": "There''s a real religion inspired by the character called Dudeism."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played ad man Don Draper on Mad Men?", "choices": ["Jon Hamm", "John Slattery", "Aaron Eckhart", "Josh Holloway"], "answer": 0, "note": "Hamm auditioned while working as a set dresser on other people''s shows... okay, as a waiter."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "''You''ll believe a man can fly'' was the tagline for which 1978 movie?", "choices": ["Flash Gordon", "Superman", "The Rocketeer", "Condorman"], "answer": 1, "note": "Marlon Brando reportedly earned millions for under 20 minutes of screen time."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "''The truth is out there'' is the slogan of which TV series?", "choices": ["Fringe", "Stranger Things", "Twin Peaks", "The X-Files"], "answer": 3, "note": "The poster hangs in Mulder''s basement office."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What year was The Shawshank Redemption released?", "choices": ["1992", "1994", "1996", "1998"], "answer": 1, "note": "It flopped in theaters, losing the Best Picture race to Forrest Gump."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What year did Goodfellas come out?", "choices": ["1988", "1990", "1992", "1995"], "answer": 1, "note": "It lost Best Picture to Dances with Wolves."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played FBI trainee Clarice Starling in The Silence of the Lambs?", "choices": ["Julianne Moore", "Sigourney Weaver", "Jodie Foster", "Michelle Pfeiffer"], "answer": 2, "note": "Anthony Hopkins won Best Actor with roughly 16 minutes of screen time."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who starred as a man unknowingly living on a TV set in The Truman Show?", "choices": ["Robin Williams", "Jim Carrey", "Tom Hanks", "Ben Stiller"], "answer": 1, "note": "''Truman Show delusion'' became a term real psychiatrists use."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "How many Oscars did The Return of the King win?", "choices": ["Nine", "Ten", "Eleven", "Thirteen"], "answer": 2, "note": "Eleven for eleven: it won every category it was nominated in."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who plays Wednesday Addams in Netflix''s Wednesday?", "choices": ["Jenna Ortega", "Millie Bobby Brown", "Sadie Sink", "Maya Hawke"], "answer": 0, "note": "Ortega choreographed the viral dance scene herself."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What is the last name of the family battling over the company in Succession?", "choices": ["Pierce", "Roy", "Logan", "Waystar"], "answer": 1, "note": "Waystar Royco is the company; Logan is the dad''s first name."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who won an Oscar for the title role in Erin Brockovich (2000)?", "choices": ["Sandra Bullock", "Charlize Theron", "Julia Roberts", "Renee Zellweger"], "answer": 2, "note": "The real Erin Brockovich has a cameo as a waitress named Julia."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "''Be afraid. Be very afraid.'' was the tagline for which 1986 remake?", "choices": ["The Blob", "Invaders from Mars", "The Thing", "The Fly"], "answer": 3, "note": "Geena Davis says the line in the movie, and it became a catchphrase."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What year was Fight Club released?", "choices": ["1997", "1999", "2001", "2003"], "answer": 1, "note": "1999 also gave us The Matrix, The Sixth Sense, and American Beauty."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who wrote and directed Get Out (2017)?", "choices": ["Jordan Peele", "Ari Aster", "Barry Jenkins", "Ryan Coogler"], "answer": 0, "note": "Peele won the Oscar for Best Original Screenplay with his debut feature."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who directed Parasite (2019)?", "choices": ["Park Chan-wook", "Bong Joon-ho", "Hirokazu Kore-eda", "Lee Chang-dong"], "answer": 1, "note": "Parasite was the first non-English-language film to win Best Picture."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "How many emotions run Riley''s head in Pixar''s Inside Out (2015)?", "choices": ["Four", "Five", "Six", "Seven"], "answer": 1, "note": "Joy, Sadness, Fear, Anger, and Disgust; the sequel added more."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played Queen Elizabeth II in the first two seasons of The Crown?", "choices": ["Olivia Colman", "Imelda Staunton", "Claire Foy", "Vanessa Kirby"], "answer": 2, "note": "All three listed queens eventually played her as the show recast with age."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "How many seasons did How I Met Your Mother run?", "choices": ["Seven", "Eight", "Nine", "Ten"], "answer": 2, "note": "The mother doesn''t fully appear until the season 8 finale."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "How many students serve Saturday detention in The Breakfast Club?", "choices": ["Four", "Five", "Six", "Seven"], "answer": 1, "note": "A brain, an athlete, a basket case, a princess, and a criminal."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "''Escape or die frying'' was the tagline for which animated film?", "choices": ["Wallace & Gromit", "Chicken Run", "Shaun the Sheep", "Madagascar"], "answer": 1, "note": "It''s basically The Great Escape with claymation chickens."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "''The first casualty of war is innocence'' sold which 1986 film?", "choices": ["Full Metal Jacket", "Apocalypse Now", "Platoon", "Born on the Fourth of July"], "answer": 2, "note": "Oliver Stone based it on his own tour in Vietnam."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What year did the first Avengers movie assemble in theaters?", "choices": ["2010", "2011", "2012", "2013"], "answer": 2, "note": "It was the first film to be built from five separate franchise lead-ins."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played icy editor Miranda Priestly in The Devil Wears Prada?", "choices": ["Glenn Close", "Meryl Streep", "Annette Bening", "Susan Sarandon"], "answer": 1, "note": "The character is widely read as a riff on Vogue''s Anna Wintour."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played Geralt of Rivia in the first three seasons of The Witcher?", "choices": ["Chris Hemsworth", "Liam Hemsworth", "Henry Cavill", "Travis Fimmel"], "answer": 2, "note": "Cavill, a fan of the games, lobbied hard for the part, then handed it to a Hemsworth."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What year did Seinfeld premiere?", "choices": ["1987", "1989", "1991", "1993"], "answer": 1, "note": "The pilot was called The Seinfeld Chronicles and nearly wasn''t picked up."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "In Whiplash (2014), what instrument does Andrew obsessively practice?", "choices": ["Piano", "Trumpet", "Guitar", "Drums"], "answer": 3, "note": "J.K. Simmons won an Oscar for hurling insults (and a chair) at him."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What is the real name of ''Baby Yoda'' in The Mandalorian?", "choices": ["Grogu", "Yaddle", "Kuiil", "Din"], "answer": 0, "note": "Din is actually the Mandalorian himself: Din Djarin."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "In Slumdog Millionaire, Jamal competes on which quiz show?", "choices": ["The Weakest Link", "Who Wants to Be a Millionaire", "Jeopardy!", "KBC Superstar"], "answer": 1, "note": "The film won eight Oscars including Best Picture."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played General Maximus in Gladiator (2000)?", "choices": ["Gerard Butler", "Joaquin Phoenix", "Mel Gibson", "Russell Crowe"], "answer": 3, "note": "Mel Gibson reportedly passed on the role before Crowe took it."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "In Home Alone, what do burglars Harry and Marv call themselves?", "choices": ["The Sticky Bandits", "The Wet Bandits", "The Home Invaders", "The Window Boys"], "answer": 1, "note": "They rebrand as the Sticky Bandits in the sequel."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played Bible-quoting hitman Jules in Pulp Fiction?", "choices": ["Samuel L. Jackson", "Ving Rhames", "Laurence Fishburne", "Denzel Washington"], "answer": 0, "note": "The Ezekiel 25:17 speech is mostly invented; only a few words match the real verse."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Who played the Bride in Kill Bill?", "choices": ["Lucy Liu", "Daryl Hannah", "Uma Thurman", "Zoe Bell"], "answer": 2, "note": "Zoe Bell was actually Thurman''s stunt double on the film."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "What year was Saving Private Ryan released?", "choices": ["1996", "1998", "2000", "2002"], "answer": 1, "note": "Its Omaha Beach opening reportedly sent some veterans out of theaters."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "Complete the Sixth Sense line: ''I see ___ ___.''", "choices": ["bad things", "dead people", "the future", "your fear"], "answer": 1, "note": "Haley Joel Osment was nominated for an Oscar at age 11."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "''One dream. Four Jamaicans. Twenty below zero.'' sold which comedy?", "choices": ["Eddie the Eagle", "Cool Runnings", "Slap Shot", "Blades of Glory"], "answer": 1, "note": "Loosely based on Jamaica''s real 1988 Olympic bobsled team."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "On Ted Lasso, what sport does Ted coach at AFC Richmond?", "choices": ["Rugby", "Soccer", "Cricket", "American football"], "answer": 1, "note": "The character began as a promo for NBC''s Premier League coverage."}'::jsonb, 2, 'trivia'),
  ('screening', null, '{"q": "''On every street in every city, there''s a nobody who dreams of being a somebody'' sold which film?", "choices": ["Taxi Driver", "Midnight Cowboy", "Joker", "Nightcrawler"], "answer": 0, "note": "De Niro''s ''You talkin'' to me?'' was improvised."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "''We are not alone'' was the tagline for which 1977 film?", "choices": ["Star Wars", "Alien", "Close Encounters of the Third Kind", "Invasion of the Body Snatchers"], "answer": 2, "note": "Its five-note alien greeting became one of cinema''s most famous melodies."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "''Man is the warmest place to hide'' sold which 1982 horror film?", "choices": ["Poltergeist", "The Thing", "The Entity", "Creepshow"], "answer": 1, "note": "John Carpenter''s remake flopped in 1982, then became a classic on video."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "''Love means never having to say you''re sorry'' comes from which 1970 film?", "choices": ["The Way We Were", "Romeo and Juliet", "A Star Is Born", "Love Story"], "answer": 3, "note": "Ryan O''Neal himself mocked the line in the 1972 comedy What''s Up, Doc?"}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "What year was Blade Runner released?", "choices": ["1979", "1982", "1984", "1986"], "answer": 1, "note": "1982 was stacked: E.T., The Thing, and Tron opened within weeks of each other."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "What year did Chinatown come out?", "choices": ["1971", "1974", "1977", "1979"], "answer": 1, "note": "Of its 11 Oscar nominations, it won just one, for the screenplay."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "What year did Twin Peaks premiere on ABC?", "choices": ["1988", "1990", "1992", "1994"], "answer": 1, "note": "''Who killed Laura Palmer?'' became a national obsession that spring."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "What year did Heat pair Pacino and De Niro in theaters?", "choices": ["1992", "1995", "1997", "1999"], "answer": 1, "note": "Their diner scene was the first time the two shared a frame on screen."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "What year was the Korean thriller Oldboy released?", "choices": ["2000", "2003", "2005", "2008"], "answer": 1, "note": "The hallway hammer fight was shot as one continuous take."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "Who played Elvira in Scarface (1983)?", "choices": ["Kim Basinger", "Kathleen Turner", "Michelle Pfeiffer", "Melanie Griffith"], "answer": 2, "note": "Pfeiffer was a near-unknown; Pacino reportedly favored another actress."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "Who played stick-up man Omar Little on The Wire?", "choices": ["Idris Elba", "Michael K. Williams", "Wendell Pierce", "Wood Harris"], "answer": 1, "note": "Barack Obama repeatedly named Omar his favorite TV character."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "Who played the liquid-metal T-1000 in Terminator 2?", "choices": ["Robert Patrick", "Edward Furlong", "Michael Biehn", "Billy Idol"], "answer": 0, "note": "Billy Idol was reportedly considered before a motorcycle crash ruled him out."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "Who played young Vito Corleone in The Godfather Part II?", "choices": ["Al Pacino", "John Cazale", "James Caan", "Robert De Niro"], "answer": 3, "note": "De Niro won the Oscar speaking almost entirely Sicilian dialect."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "Who played Nurse Ratched in One Flew Over the Cuckoo''s Nest?", "choices": ["Ellen Burstyn", "Faye Dunaway", "Louise Fletcher", "Anne Bancroft"], "answer": 2, "note": "The film swept all five major Oscars, a feat managed only three times ever."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "The Color Purple (1985) got 11 Oscar nominations. How many did it win?", "choices": ["Zero", "One", "Three", "Five"], "answer": 0, "note": "It tied the record for most nominations without a single win."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "How many seasons did M*A*S*H run?", "choices": ["Seven", "Nine", "Eleven", "Thirteen"], "answer": 2, "note": "The show ran 11 years covering a war that lasted three."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "How many Oscars did Amadeus (1984) win?", "choices": ["Four", "Six", "Eight", "Ten"], "answer": 2, "note": "Two of its stars competed against each other for Best Actor; F. Murray Abraham won."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "In The Princess Bride, who is the six-fingered man?", "choices": ["Prince Humperdinck", "Count Rugen", "Vizzini", "Fezzik"], "answer": 1, "note": "''Hello. My name is Inigo Montoya. You killed my father. Prepare to die.''"}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "Frasier is a spin-off of which sitcom?", "choices": ["Taxi", "Wings", "Night Court", "Cheers"], "answer": 3, "note": "Frasier Crane appeared in over 400 combined episodes across the two shows."}'::jsonb, 3, 'trivia'),
  ('screening', null, '{"q": "''His story will touch you, even though he can''t'' sold which Tim Burton film?", "choices": ["Beetlejuice", "Big Fish", "Edward Scissorhands", "Corpse Bride"], "answer": 2, "note": "It was the first of eight collaborations between Burton and Johnny Depp."}'::jsonb, 3, 'trivia');
